 /"\n"
 |
@j/"This was a Triumph."
  |"I'm making a note here, HUGE SUCCESS!"
  |"It's hard to overstate my satisfaction!"
  |"APETURE SCIENCE!"
  |"We do what we must, Because, We can."
  |"For the good of all of us"
  |"EXCEPT THE ONES WHO ARE DEAD"
  |"But there's no sense crying over every mistake."
  |"You just keep on trying 'till you run out of cake."
  |"And the science gets done"
  |"And you make a need gun"
  |"For the people who are"
  |"STILL ALIVE"